# Makefile for Beginning Linux Programming 3rd Edition
# Chapter 5

CC=gcc

MENU=menu1 menu2 menu3 menu4
TERMIOS=password badterm sizeterm

LDFLAGS=-lncurses

ALL= $(MENU) $(TERMIOS)

all: $(ALL) 

clean:
	@rm -f $(ALL) *~
